export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCHING_POKEMON = 'FETCHING_POKEMON';
export const FETCH_POKEMON_FAILED = 'FETCH_POKEMON_FAILED';
export const FETCH_POKEMON_DETAILS_SUCCESS = 'FETCH_POKEMON_DETAILS_SUCCESS';
export const SET_POKEMON_DETAILS_SUCCESS = 'SET_POKEMON_DETAILS_SUCCESS';
export const SET_POKEMON_DETAILS_FAILED = 'SET_POKEMON_DETAILS_FAILED';
